eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: vagetable-user
    #连接数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.221.197:3306/user?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: yourpassword

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update #自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表
    show-sql: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #设置重启目录