server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  routes:
    Vegetable-User:
      path: /V1.0/**
      serviceId: vagetable-user
  add-host-header: true
  add-proxy-headers: true
eureka:
  client:
    serviceUrl:
      defaulyZone: http://localhost:8761/eureka/