server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  routes:
    Vegetable-User:
      path: /v1.0/**
      serviceId: vagetable-user
  add-host-header: true
  add-proxy-headers: true
  host:
    socket-timeout-millis: 60000  #socket超时
    connect-timeout-millis: 65000 #HTTP链接超时要比Hystrix的大
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutlnMilliseconds: 60000  #设置超时时间 60秒
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
eureka:
  client:
    serviceUrl:
      defaulyZone: http://localhost:8761/eureka/